/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   saved-request-detail.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/legacy/class.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../http-method-label/http-method-label.d.ts" />
/// <reference path="../date-time/date-time.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../iron-resizable-behavior/iron-resizable-behavior.d.ts" />
/// <reference path="../marked-element/marked-element.d.ts" />
/// <reference path="../markdown-styles/markdown-styles.d.ts" />
/// <reference path="../paper-chip/paper-chip.d.ts" />

declare namespace UiElements {

  /**
   * Details applet for saved request object.
   *
   * If the request is a history item the set `isHistory` property to `true`.
   *
   * The applet doesn't support data edit. Element / app hosting this element
   * must handle events sent by this element and support edit action.
   *
   * ### Example
   *
   * ```html
   * <saved-request-detail request="{...}"></saved-request-detail>
   * ```
   *
   * ### Styling
   *
   * `<saved-request-detail>` provides the following custom properties and
   * mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--saved-request-detail` | Mixin applied to the element | `{}`
   * `--saved-request-detail-description` | Mixin applied to request description | `{}`
   * `--saved-request-detail-description-max-width` | Max width of the description element | `700px`
   * `--saved-request-detail-description-color` | Color of the request description |
   * `rgba(0, 0, 0, 0.64)`
   * `--saved-request-detail-url-label` | Mixin applied to the  URL label | `{}`
   * `--saved-request-detail-method-label` | Mixin applied to the `http-method-label` element | `{}`
   * `--saved-request-detail-meta-row` | Mixin applied to the meta data list items | `{}`
   * `--saved-request-detail-meta-row-label` | Mixin applied to the meta data label | `{}`
   * `--saved-request-detail-meta-row-value` | Mixin applied to the meta data value | `{}`
   * `--saved-request-detail-actions-container` | Mixin applied to the buttons container | `{}`
   * `--saved-request-detail-action-buttons` | Mixin applied to the action buttons | `{}`
   * `--saved-request-detail-action-icon` | Mixin applied to action buttons icons  | `{}`
   * `--saved-request-detail-action-icon-color` | Color of the icon in the action
   * button | `rgba(0, 0, 0, 0.54)`
   */
  class SavedRequestDetail extends
    Polymer.IronResizableBehavior(
    Polymer.Element) {

    /**
     * Request object to render.
     */
    request: object|null|undefined;

    /**
     * True if current item represent a history item.
     */
    isHistory: boolean|null|undefined;

    /**
     * Projects data associated with the request.
     */
    _projects: Array<object|null>|null;

    /**
     * Sets project data when `request` object change.
     */
    _requestChanged(request: object|null): void;

    /**
     * Reads related project data.
     */
    _readProjects(ids: any): void;

    /**
     * Sends `navigate` event set to current read project.
     */
    _openProject(e: ClickEvent|null): void;

    /**
     * Sends non-bubbling `delete-request` event to the parent element to perform
     * delete action.
     */
    _deleteRequest(): void;

    /**
     * Sends non-bubbling `edit-request` event to the parent element to perform
     * edit action.
     */
    _editRequest(): void;
  }
}

interface HTMLElementTagNameMap {
  "saved-request-detail": UiElements.SavedRequestDetail;
}
